name: 'Lint VBA'
description: 'Lint VBA source code.'
branding:
  icon: "sun"
  color: "red"
inputs:
  path:
    description: 'Path to source files.'
    default: "."
runs:
  using: "composite"
  steps:
    - run: |
        pip install --upgrade pip 
        python -m pip install https://github.com/Beakerboy/VBA-Linter/archive/dev.zip
      shell: bash
    - env:
        FULLPATH: "${{ github.workspace }}/${{ inputs.path }}"
      run: |
        pip list
        python -m vba_linter $FULLPATH
      shell: bash
