name: 'Lint VBA'
description: 'Lint VBA source code.'
branding:
  icon: "sun"
  color: "red"
inputs:
  path:
    description: 'Path to source files.'
    default: "."
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v1
    - run: |
        python -m pip install https://github.com/user/repository/archive/branch.zip
      shell: bash
    - env:
        FULLPATH: "${{ github.workspace }}/${{ inputs.path }}"
      run: |
        python -m vba_linter $FULLPATH
      shell: bash
