name: 'Lint'
description: 'Lint VBA source code.'
inputs:
  path:
    description: 'Path to source files.'
    default: ${{ github.repository }}
runs:
  using: "composite"
  steps:
    - run: |
        cd ${{ github.repository }}
        python -m pip install antlr4-tools
        wget https://raw.githubusercontent.com/Beakerboy/VBA_Tokenizer/ANTLR/VbaLint
        chmod +x VbaLint
      shell: bash
    - run: |
        cd ${{ inputs.who-to-greet }}
        ${{ github.repository }}/VbaLint
      shell: bash
